name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@1.81.0
        with:
          components: clippy, rustfmt
      - name: Setup rust cache
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # 2.7.7
        with:
          cache-all-crates: true
          key: ci-build-v1
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@65101d47ea8028ed0c98a1cdea8dd9182e9b5133 # v0.0.8
        with:
          version: v0.8.2
      - name: Build
        run: cargo build --workspace
      - name: Cargo fmt
        run: cargo fmt --all --check
      - name: Clippy check
        run: cargo clippy --no-deps --workspace --tests -- -Dwarnings

  tests:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@1.81.0
      - name: Setup rust cache
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # 2.7.7
        with:
          cache-all-crates: true
          key: ci-test-v1
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@65101d47ea8028ed0c98a1cdea8dd9182e9b5133 # v0.0.8
        with:
          version: v0.8.2
      - name: Setup just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2
      - name: Run tests
        run: just test

  contracts:
    name: Build Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2
      - name: Test
        run: just build-contracts

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@1.81.0
      - name: Setup rust cache
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # 2.7.7
        with:
          cache-all-crates: true
          key: ci-lint-v1
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@65101d47ea8028ed0c98a1cdea8dd9182e9b5133 # v0.0.8
        with:
          version: v0.8.2
      - name: Install cargo-machete
        uses: clechasseur/rs-cargo@8435b10f6e71c2e3d4d3b7573003a8ce4bfc6386 # v2.0.6
        with:
          command: install
          args: cargo-machete@0.7.0
      - name: Machete
        uses: clechasseur/rs-cargo@8435b10f6e71c2e3d4d3b7573003a8ce4bfc6386 # v2.0.6
        with:
          command: machete
      - name: Cargo audit
        uses: rustsec/audit-check@dd51754d4e59da7395a4cd9b593f0ff2d61a9b95
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
