[package]
name = "kademlia-discovery"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
kolme = { workspace = true }
libp2p = { workspace = true, features = ["dns", "rsa"] }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
tracing = { workspace = true }
