# Kolme git-cliff configuration - Keep a Changelog style

[git]
tag_pattern = "v[0-9]*"
repository = "https://github.com/fpco/kolme"

[cli]
output = "CHANGELOG.md"

[changelog]
group_by = "title"
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), and this changelog is generated automatically from commit history using [git-cliff](https://github.com/orhun/git-cliff).

"""

group_titles.Added = "Added"
group_titles.Changed = "Changed"
group_titles.Deprecated = "Deprecated"
group_titles.Removed = "Removed"
group_titles.Fixed = "Fixed"
group_titles.Security = "Security"
group_titles.Documentation = "Documentation"
group_titles.Tests = "Tests"
group_titles.Build = "Build System"
group_titles.CI = "Continuous Integration"
group_titles.Chores = "Chores"

group = """
### {{ group | upper_first }}
"""

body = """
{% if version %}
## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
## [Unreleased]
{% endif %}

{% if commits | length == 0 %}
_No changes._
{% else %}
{% for group, commits in commits | group_by(attribute="group") %}
{{ group }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ({{ commit.id | truncate(length=7) }})
{% endfor %}
{% endfor %}
{% endif %}
"""

footer = """
---
For previous versions and more details, see the project repository.
"""

[[changelog.commit_groups]]
title = "Added"
regex = "^feat"
order = 1

[[changelog.commit_groups]]
title = "Changed"
regex = "^(refactor|perf)"
order = 2

[[changelog.commit_groups]]
title = "Deprecated"
regex = "^deprecate"
order = 3

[[changelog.commit_groups]]
title = "Removed"
regex = "^remove"
order = 4

[[changelog.commit_groups]]
title = "Fixed"
regex = "^fix"
order = 5

[[changelog.commit_groups]]
title = "Security"
regex = "^security"
order = 6

[[changelog.commit_groups]]
title = "Documentation"
regex = "^docs"
order = 7

[[changelog.commit_groups]]
title = "Tests"
regex = "^test"
order = 8

[[changelog.commit_groups]]
title = "Build"
regex = "^build"
order = 9

[[changelog.commit_groups]]
title = "CI"
regex = "^ci"
order = 10

[[changelog.commit_groups]]
title = "Chores"
regex = "^chore"
order = 11

[commit_parsers]
conventional = true
