SOLANA_VERSION := "2.2.18"

# List all recipes
default:
	just --list --unsorted

# Build
build:
  GIT_REV=$(git rev-parse HEAD) cargo build-sbf -- --lib

# Compile
cargo-compile:
  cargo test -p testing --no-run --locked

# Test
test:
  cargo test --locked -p testing

# Download solana tool
download-solana:
	curl -L -o solana-release.tar.bz2 https://github.com/anza-xyz/agave/releases/download/v{{SOLANA_VERSION}}/solana-release-x86_64-unknown-linux-gnu.tar.bz2
	tar xjf solana-release.tar.bz2
	-rm ~/.cargo/bin/perf-libs
	-rm ~/.cargo/bin/platform-tools-sdk
	-rm ~/.cargo/bin/deps
	mv solana-release/bin/* ~/.cargo/bin/
	rm solana-release.tar.bz2
	rm -rf solana-release
