[package]
name = "kolme-zkp-auth"
version = "0.1.0"
edition = "2021"
authors = ["Kolme Contributors"]
description = "Zero-knowledge proof authentication for Kolme"
license = "MIT OR Apache-2.0"

[dependencies]
# ZKP libraries
ark-std = "0.4"
ark-ff = "0.4"
ark-bls12-381 = "0.4"
ark-groth16 = "0.4"
ark-relations = "0.4"
ark-serialize = "0.4"
ark-snark = "0.4"
ark-crypto-primitives = { version = "0.4", features = ["crh"] }
ark-sponge = "0.4.0-alpha"

# Kolme dependencies
shared = { workspace = true }

# Async runtime
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"

# Error handling
anyhow = "1"
thiserror = "1"
snafu = "0.8"

# Utilities
tracing = "0.1"
hex = "0.4"
sha2 = "0.10"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4"

# R1CS
ark-r1cs-std = "0.4"

# HTTP and OAuth
urlencoding = "2"
reqwest = { version = "0.11", features = ["json"] }
oauth2 = "4"
base64 = "0.21"

[dev-dependencies]
tokio-test = "0.4"
proptest = "1"
criterion = "0.5"
tempfile = "3"

[[bin]]
name = "setup"
path = "src/bin/setup.rs"

[dependencies.blake3]
version = "1.5"