[package]
name = "merkle-map"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
base64 = "0.22.1"
parameterized = "2.0.0"
parking_lot = "0.12.3"
rust_decimal = { workspace = true }
sha2 = "0.10.9"
serde = { version = "1.0.218", features = ["derive"] } # 
serde_json = { workspace = true }
shared = { workspace = true, features = ["realcryptography"] }
thiserror = "2.0.12"
tinyvec = { version = "1.9.0", features = ["alloc"] }
jiff = { workspace = true }
smallvec = { version = "1.13.2", default-features = false }

[dev-dependencies]
paste = "1.0.15"
quickcheck = { workspace = true }
tokio = { version = "1.43.0", features = ["full"] }
