[package]
name = "merkle-map"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { workspace = true }
base64 = { workspace = true }
jiff = { workspace = true }
lru.workspace = true
parameterized = { workspace = true }
parking_lot = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shared = { workspace = true, features = ["realcryptography"] }
smallvec = { workspace = true }
thiserror = { workspace = true }
tinyvec = { workspace = true, features = ["alloc"] }

[dev-dependencies]
paste = { workspace = true }
quickcheck = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true
