[package]
name = "merkle-map"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
rust_decimal = { version = "1.37.1" }
serde = "1.0.218"
serde_json = "1.0.140"
shared = { workspace = true, features = ["realcryptography"] }
thiserror = "2.0.12"
tinyvec = { version = "1.9.0", features = ["alloc"] }

[dev-dependencies]
quickcheck = "1.0.3"
tokio = { version = "1.43.0", features = ["full"] }
