[package]
name = "merkle-map"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
parameterized = "2.0.0"
parking_lot = "0.12.3"
rust_decimal = { workspace = true }
serde = "1.0.218"
serde_json = { workspace = true }
shared = { workspace = true, features = ["realcryptography"] }
thiserror = "2.0.12"
tinyvec = { version = "1.9.0", features = ["alloc"] }

[dev-dependencies]
paste = "1.0.15"
quickcheck = { workspace = true }
tokio = { version = "1.43.0", features = ["full"] }
