[package]
name = "version-upgrade"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap = { workspace = true }
ed25519-dalek = "2.1.1"
hex.workspace = true
kolme.workspace = true
libp2p.workspace = true
merkle-map.workspace = true
rand = "0.8"
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.10.9"
tokio = { workspace = true }

