services:
  localosmosis:
    container_name: localosmosis
    build:
      context: ./docker-resources/localosmosis
    ports:
      - "127.0.0.1:26657:26657"
      - "127.0.0.1:1317:1317"
      - "127.0.0.1:9090:9090"
      - "127.0.0.1:9091:9091"
    volumes:
      - ./local-workspace:/var/workspace

  postgres:
    container_name: postgres
    image: "postgres:16"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5432:5432"
