services:
  localosmosis:
    container_name: localosmosis
    image: "ghcr.io/fpco/cosmos-images/localosmosis:3703be0654109bd04d6e4e1f7d2707ea905a28eb"
    ports:
      - "127.0.0.1:26657:26657"
      - "127.0.0.1:1317:1317"
      - "127.0.0.1:9090:9090"
      - "127.0.0.1:9091:9091"
    networks:
      - app_net
  postgres:
    container_name: postgres
    image: "postgres:16"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:45921:5432"
    networks:
      - app_net


networks:
  app_net:
    driver: bridge
