[package]
name = "example-cosmos-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
reqwest = { version = "0.12.15", features = ["json"] }
rand = "0.8"
tokio = { workspace = true }
clap = { workspace = true }
kolme = { workspace = true }
cosmos = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
jiff = { workspace = true }
