[package]
name = "merkle-store-fjall"
version = "0.1.0"
edition = "2021"

[dependencies]
fjall.workspace = true
merkle-map.workspace = true
smallvec.workspace = true

[dev-dependencies]
quickcheck.workspace = true
